// This file is automatically generated. Do not modify it.
// To update this file, create a new Firebase project and run the "firebase:bootstrap" command.

import {FirebaseOptions} from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  projectId: 'studio-1813050691-7be9c',
  appId: '1:670089868593:web:9fd6c35fdcc53baed92c10',
  apiKey: 'AIzaSyAUeOIb4BFFC0vsqxlV8TSFFi73eLuEs6o',
  authDomain: 'studio-1813050691-7be9c.firebaseapp.com',
  messagingSenderId: '670089868593',
};
